### ISSUE TITLE
Prompt issue

### ISSUE THREAD

**Issue by mvivier001** [fullfox/shellshot#1]
`Script started on 2024-03-01 15:47:55+01:00 [TERM="xterm-256color" TTY="/dev/pts/10" COLUMNS="135" LINES="36"]$
                                                                                                                                       ^M^M^[]0;root@5CG2521VF3: /home/mvivier^G^M^[[0m^[[27m^[[24m^[[J^[[34mM-bM-^TM-^LM-bM-^TM-^@M-bM-^TM-^@(^[[1m^[[34m^[[31mrootM-cM-^IM-?5CG2521VF3^[[0m^[[31m^[[34m)-[^[[1m^[[34m^[[39m/home/mvivier^[[0m^[[34m]^M$
M-bM-^TM-^TM-bM-^TM-^@^[[1m^[[34m^[[31m#^[[0m^[[31m^[[39m ^[[K^[[?1h^[=^[[?2004h^[[4m^[[37mp^[[24m^[[39m^H^[[4m^[[37mp^[[24m^[[39m^[[38;2;153;153;153ming 10.123.124.51^[[39m^[[17D^H^[[24m^[[36mp^[[36ms^[[39m^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[16D^[[38;2;153;153;153m aux|grep -i teams|awk -F ' ' '{print $2}' | xargs kill -9^[[39m^[[58D^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[39m ^[[58D^[[?1l^[>^[[?2004l^M^M$
    PID TTY          TIME CMD^M$
  24284 pts/11   00:00:00 zsh^M$
  24367 pts/11   00:00:00 ps^M$
                                                                                                                                       ^M^M^[]0;root@5CG2521VF3: /home/mvivier^G^M$
^M^[[0m^[[27m^[[24m^[[J^[[34mM-bM-^TM-^LM-bM-^TM-^@M-bM-^TM-^@(^[[1m^[[34m^[[31mrootM-cM-^IM-?5CG2521VF3^[[0m^[[31m^[[34m)-[^[[1m^[[34m^[[39m/home/mvivier^[[0m^[[34m]^M$
M-bM-^TM-^TM-bM-^TM-^@^[[1m^[[34m^[[31m#^[[0m^[[31m^[[39m ^[[K^[[?1h^[=^[[?2004h^[[1me^[[0m^H^[[1me^[[0m^[[38;2;153;153;153mxit^[[39m^H^H^H^H^[[0m^[[36me^[[36mx^[[39m^H^H^[[4m^[[37me^[[4m^[[37mx^[[4m^[[37mi^[[24m^[[39m^H^H^H^[[24m^[[36me^[[24m^[[36mx^[[24m^[[36mi^[[36mt^[[39m^[[?1l^[>^[[?2004l^M^M$
$
Script done on 2024-03-01 15:48:06+01:00 [COMMAND_EXIT_CODE="0"]$`

**Comment by TheProtyro** [comment]
Same issue than Mathieu.

```
Script started on 2024-03-01 15:59:30+01:00 [TERM="tmux-256color" TTY="/dev/pts/3" COLUMNS="172" LINES="40"]$
                                                                                                                                                                            ^M^M^M^[[0m^[[27m^[[24m^[[J[01/03/2024 15:59:30] ^[[1m^[[31mroot@DESKTOP-XL1CDGM^[[0m^[[31m^[[39m:^[[1m^[[34m~/toto^[[0m^[[34m^[[39m# ^[[K^[[?1h^[=^[[?2004h^[[32ml^[[39m^H^[[32ml^[[39m^[[38;2;153;153;153ms^[[39m^H^H^[[32ml^[[32ms^[[39m^[[?1l^[>^[[?2004l^M^M$
typescript^M$
                                                                                                                                                                            ^M^M^M^[[0m^[[27m^[[24m^[[J[01/03/2024 15:59:32] ^[[1m^[[31mroot@DESKTOP-XL1CDGM^[[0m^[[31m^[[39m:^[[1m^[[34m~/toto^[[0m^[[34m^[[39m# ^[[K^[[?1h^[=^[[?2004h^[[1m^[[31me^[[0m^[[39m^H^[[1m^[[31me^[[0m^[[39m^[[38;2;153;153;153mxit^[[39m^H^H^H^H^[[0m^[[32me^[[32mx^[[39m^H^H^[[1m^[[31me^[[1m^[[31mx^[[1m^[[31mi^[[0m^[[39m^H^H^H^[[0m^[[32me^[[0m^[[32mx^[[0m^[[32mi^[[32mt^[[39m^[[?1l^[>^[[?2004l^M^M$
$
Script done on 2024-03-01 15:59:35+01:00 [COMMAND_EXIT_CODE="0"]$
```

**Comment by fullfox** [comment]
did some fixes, pls retest

**Comment by Mauriceter** [comment]
fixed :) 5/5 for reactivity, thx!

**Comment by TheProtyro** [comment]
Also fixed on my side. Thanks FullFox, the GOAT sharing GOT. 🐐
